routes/web.php
<?php
use zcrmsdk\crm\setup\restclient\ZCRMRestClient;
use zcrmsdk\crm\crud\ZCRMCustomView;
use zcrmsdk\crm\crud\ZCRMRecord;
use zcrmsdk\crm\exception\ZCRMException;
use CristianPontes\ZohoCRMClient\ZohoCRMClient;

Route::get('storage/{filename}', function ($filename)
{
    $path = storage_path('app/public/' . $filename);
    if (!File::exists($path)) {
        abort(404);
    }
    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

Auth::routes();

Route::get('/', ['uses' => 'HomeController@index', 'as' => 'app.home.index']);
Route::get('/about-us', ['uses' => 'HomeController@about', 'as' => 'app.home.about']);
Route::get('/contact-us', ['uses' => 'HomeController@contact', 'as' => 'app.home.contact']);
Route::get('/terms', ['uses' => 'HomeController@terms', 'as' => 'app.home.term']);
Route::get('/privacy', ['uses' => 'HomeController@privacy', 'as' => 'app.home.privacy']);

Route::get('/callback', function(){
    $configuration = array("client_id"=>"1000.3QS1SQ0HC68N067758TLG97ECN9N1H",
    "client_secret"=>"5c1d0eaff7b057a591d66506ee3126925a3e15103b",
    "redirect_uri"=>"https://sdc-system.app/",
    "currentUserEmail"=>"khaled@sdccards.com"); 
    

    $client = new ZohoCRMClient('Leads', 'b49f3c7aebceccba8cc3bddd087b34da');

    $records = $client->getRecords()
        ->selectColumns('First Name', 'Last Name', 'Email')
        ->sortBy('Last Name')->sortAsc()
        ->since(date_create('last week'))
        ->request();

    // Just for debug
    echo "<pre>";
    print_r($records);
    echo "</pre>";

});

Route::group(['middleware' => 'auth'], function () {
    Route::resource('/user', 'UserController');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Cache;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'fname', 'lname', 'email', 'password', 'phone', 'balance', 'member_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function timetables()
    {
        return $this->belongsToMany('App\Timetable', 'users_timetables', 'user_id', 'timetable_id');
    }

    public function exercises()
    {
        return $this->belongsToMany('App\Exercise', 'users_exercises', 'user_id', 'exercise_id');
    }

    public function bookings()
    {
        return $this->hasMany('App\Booking');
    }

    public function getFullNameAttribute()
    {
        return $this->fname .' '. $this->lname;
    }

    public function isConfirmedBooked(Timetable $timetable)
    {
        $record = $this->bookings()->where('timetable_id', $timetable->id)->first();

        if(! is_null($record) && $record->is_confirmed == 1)
        {
            return true;
        }

        return false;
    }

    public function isPendingBooked(Timetable $timetable)
    {
        $record = $this->bookings()->where('timetable_id', $timetable->id)->first();
        if(! is_null($record) && $record->is_confirmed == 0)
        {
            return true;
        }

        return false;
    }

    public function isRegistered(Exercise $exercise)
    {
        $record = $this->exercises()->where('exercise_id', $exercise->id)->where('user_id', $this->id)->first();
        if(! is_null($record))
        {
            return true;
        }

        return false;
    }

    public function hasBooked(Timetable $timetable)
    {
        if($this->bookings()
            ->whereDate('date', '>=', now())
            ->where('timetable_id', $timetable->id)
            ->first())
        {
            return true;
        }

        return false;
    }

    public function getExercisePercentage()
    {
        $exercise_count = Cache::get('exercises')->count();
        $user_exercise_count = $this->exercises()->count();
        
        if($user_exercise_count == 0 || $user_exercise_count == 0)
        {
            return 0;
        }

        return intval($user_exercise_count / $exercise_count * 100);
    }

    // من اصل جميع الحجوزات
    public function getConfimredBookingPercentage()
    {
        $user_booking_count = $this->bookings()->count();
        $user_confirmed_booking_count = $this->bookings()->where('is_confirmed', true)->count();
        
        if($user_booking_count == 0)
        {
            return 0;
        }
        
        return intval($user_confirmed_booking_count / $user_booking_count * 100);
    }

    public function getCancellationPercentage()
    {
        return 0;
    }
}

resources/views/partials/breadcrumbs.blade.php
<div class="breadcrumbs-wrap no-title">
    <div class="container">
        <ul class="breadcrumbs">
            <li><a href="{{ url('/') }}">الصفحة الرئيسية</a></li>
            @if(! is_null(\Request::segment(1)) && is_null(\Request::segment(2)))
            <li><a href="{{ url('/' . \Request::segment(1)) }}">{{ __('breadcrumbs.' . \Request::segment(1))}}</a></li>
            @endif
            @if(! is_null(\Request::segment(1)) && ! is_null(\Request::segment(2)))
            <li><a href="#">{{ __('breadcrumbs.' . \Request::segment(1))}}</a></li>
            <li><a href="{{ url('/' . \Request::segment(1) .'/'.\Request::segment(2) ) }}">@yield('title')</a></li>
            @endif
        </ul>
    </div>
</div>

resources/views/partials/errors.blade.php
@if ($errors->any())
<div class="alert alert-error">
	<button type="button" class="close" data-dismiss="alert"></button>
	@foreach ($errors->all() as $error)
		<p>{{ $error }}</p>
	@endforeach
</div>
@endif

@if(session('message'))
<div class="container">
<div class="alert alert-success">
<button type="button" class="close" data-dismiss="alert"></button>
{{ session('message') }}
</div>
</div>
@endif

resources/views/partials/footer.blade.php
<!-- START FOOTER -->
<footer class="bg_gray">
	<div class="top_footer small_pt small_pb">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                	<div class="footer_logo">
                    	<a href="index.html"><img alt="logo" src="assets/images/logo_dark.png"></a>
                    </div>
                    <div class="footer_desc">
                    	<p>Phasellus blandit massa enim. elit id varius nunc. Lorems ipsum dolor sit consectetur industry. If you are going to use a passage of Lorem Ipsum.</p>
                    </div>
                    <ul class="contact_info list_none">
                    	<li>
                            <span class="ti-mobile"></span>
                            <p>+123 456 7890</p>
                        </li>
                        <li>
                            <span class="ti-email"></span>
                            <a href="mailto:info@yourmail.com">info@yourmail.com</a>
                        </li>
                        <li>
                            <span class="ti-location-pin"></span>
                            <address>123 Street, Old Trafford, NewYork, USA</address>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-4">
                	<h5 class="widget_title">Information</h5>
                    <ul class="list_none widget_links">
                    	<li><a href="#">Delivery Information</a></li>
                        <li><a href="#">Secure Payment</a></li>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Top Sellers</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Our Sitemap</a></li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-4">
                	<h5 class="widget_title">Customer Support</h5>
                    <ul class="list_none widget_links">
                    	<li><a href="#">My Account</a></li>
                        <li><a href="#">Shopping Cart</a></li>
                        <li><a href="#">Addresses</a></li>
                        <li><a href="#">Discount</a></li>
                        <li><a href="#">Orders History</a></li>
                        <li><a href="#">Order Tracking</a></li>
                    </ul>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-4">
                	<h5 class="widget_title">Instagram</h5>
                    <ul class="list_none instafeed">
                    	<li><a href="#"><img src="assets/images/insta_img1.jpg" alt="insta_img"><span class="insta_icon"><i class="ti-instagram"></i></span></a></li>
                        <li><a href="#"><img src="assets/images/insta_img2.jpg" alt="insta_img"><span class="insta_icon"><i class="ti-instagram"></i></span></a></li>
                        <li><a href="#"><img src="assets/images/insta_img3.jpg" alt="insta_img"><span class="insta_icon"><i class="ti-instagram"></i></span></a></li>
                        <li><a href="#"><img src="assets/images/insta_img4.jpg" alt="insta_img"><span class="insta_icon"><i class="ti-instagram"></i></span></a></li>
                        <li><a href="#"><img src="assets/images/insta_img5.jpg" alt="insta_img"><span class="insta_icon"><i class="ti-instagram"></i></span></a></li>
                        <li><a href="#"><img src="assets/images/insta_img6.jpg" alt="insta_img"><span class="insta_icon"><i class="ti-instagram"></i></span></a></li>
                        <li><a href="#"><img src="assets/images/insta_img7.jpg" alt="insta_img"><span class="insta_icon"><i class="ti-instagram"></i></span></a></li>
                        <li><a href="#"><img src="assets/images/insta_img8.jpg" alt="insta_img"><span class="insta_icon"><i class="ti-instagram"></i></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="middle_footer">
    	<div class="container">
        	<div class="row">
            	<div class="col-12">
                	<div class="shopping_info">
                        <div class="row justify-content-center">
                            <div class="col-md-4">	
                                <div class="icon_box icon_box_style2">
                                    <div class="box_icon">
                                        <i class="fas fa-truck"></i>
                                    </div>
                                    <div class="intro_desc">
                                    	<h5>Free Delivery</h5>
                                        <p>Phasellus blandit massa enim elit of passage varius nunc.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">	
                                <div class="icon_box icon_box_style2">
                                    <div class="box_icon">
                                        <i class="fas fa-dollar-sign"></i>
                                    </div>
                                    <div class="intro_desc">
                                    	<h5>30 Day Returns Guarantee</h5>
                                        <p>Phasellus blandit massa enim elit of passage varius nunc.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">	
                                <div class="icon_box icon_box_style2">
                                    <div class="box_icon">
                                        <i class="far fa-life-ring"></i>
                                    </div>
                                    <div class="intro_desc">
                                    	<h5>27/4 Online Support</h5>
                                        <p>Phasellus blandit massa enim elit of passage varius nunc.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom_footer">
    	<div class="container">
        	<div class="row align-items-center">
            	<div class="col-lg-4">
                    <p class="copyright m-lg-0 text-center">Copyright © 2019 All Rights Reserved </p>
                </div>
                <div class="col-lg-4 order-lg-first">
                    <ul class="list_none footer_payment text-center text-lg-left">
                        <li><a href="#"><img src="assets/images/visa.png" alt="visa"/></a></li>
                        <li><a href="#"><img src="assets/images/discover.png" alt="discover"/></a></li>
                        <li><a href="#"><img src="assets/images/master_card.png" alt="master_card"/></a></li>
                        <li><a href="#"><img src="assets/images/paypal.png" alt="paypal"/></a></li>
                        <li><a href="#"><img src="assets/images/amarican_express.png" alt="amarican_express"/></a></li>
                    </ul>
                </div>
                <div class="col-lg-4">
                    <ul class="list_none social_icons radius_social text-center text-lg-right">
                        <li><a href="#" class="sc_facebook"><i class="fab fa-facebook-f"></i></a></li>
                        <li><a href="#" class="sc_twitter"><i class="fab fa-twitter"></i></a></li>
                        <li><a href="#" class="sc_google"><i class="fab fa-google-plus-g"></i></a></li>
                        <li><a href="#" class="sc_instagram"><i class="fab fa-instagram"></i></a></li>
                        <li><a href="#" class="sc_pinterest"><i class="fab fa-pinterest"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="overlap_shape">
        <div class="ol_shape21">
            <div class="animation">
                <img data-parallax='{"y": 20, "smoothness": 20}' src="assets/images/shape36.png" alt="shape36"/>
            </div>
        </div>
        <div class="ol_shape22">
            <div class="animation">
                <img data-parallax='{"y": 20, "smoothness": 20}' src="assets/images/shape37.png" alt="shape37"/>
            </div>
        </div>
        <div class="ol_shape23">
            <div class="animation">
                <img data-parallax='{"y": 20, "smoothness": 20}' src="assets/images/shape38.png" alt="shape38"/>
            </div>
        </div>
        <div class="ol_shape24">
            <div class="animation">
                <img data-parallax='{"y": 20, "smoothness": 20}' src="assets/images/shape39.png" alt="shape39"/>
            </div>
        </div>
    </div>
</footer>
<!-- END FOOTER -->

resources/views/partials/header.blade.php
<!-- START HEADER -->
<header class="header_wrap dark_skin main_menu_uppercase">
	<div class="top-header bg_gray">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-7">
                    <ul class="contact_detail border_list list_none text-center text-md-left">
                        <li>
                            <div class="custome_dropdown">
                                <select name="countries" class="custome_select">
                                    <option value='en' data-title="English">English</option>
                                    <option value='fn' data-title="العربية">العربية</option>
                                </select>
                            </div>
                        </li>
                        <li>
                          <a href="#">إشترك اﻵن</a>
                        </li>
                        <li>
                          <a href="#">تسجيل دخول</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-5">
                    <ul class="contact_detail border_list list_none text-center text-md-right">
                        <li><a href="#"><i class="ti-mobile"></i> <span>+123 456 7890</span></a></li>
                        <li><a href="#"><i class="ti-email"></i> <span>info@sdccards.com</span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <nav class="navbar navbar-expand-lg"> 
            <a class="navbar-brand" href="index.html">
                <img class="logo_light" src="assets/images/logo_white.png" alt="logo" />
                <img class="logo_dark" src="assets/images/logo_dark.png" alt="logo" />
                <img class="logo_default" src="assets/images/logo_dark.png" alt="logo" />
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="ion-android-menu"></span> </button>
            <div class="collapse navbar-collapse navbar-rtl" id="navbarSupportedContent">
				<ul class="navbar-nav">
                    <li>
                        <a class="nav-link" href="/">الصفحة الرئيسية</a>
                    </li>
                    <li class="dropdown dropdown-mega-menu">
                        <a class="dropdown-toggle nav-link" href="#" data-toggle="dropdown">الماركات</a>
                        <div class="dropdown-menu">
                            <ul class="mega-menu d-lg-flex">
                            	<li class="mega-menu-col col-lg-3">
                                    <ul> 
                                        <li class="dropdown-header">Shop Pages</li> 
                                        <li><a class="dropdown-item nav-link nav_item" href="shop-list-view.html">Shop List View</a></li>
                                        <li><a class="dropdown-item nav-link nav_item" href="shop-grid-view.html">Shop Grid View</a></li>
                                        <li><a class="dropdown-item nav-link nav_item" href="shop-three-columns.html">shop 3 Column</a></li>
                                        <li><a class="dropdown-item nav-link nav_item" href="shop-four-columns.html">shop 4 Column</a></li>
                                    </ul>
                                </li>
                                <li class="mega-menu-col col-lg-3">
                                    <ul> 
                                        <li class="dropdown-header">Product Detail</li> 
                                        <li><a class="dropdown-item nav-link nav_item" href="product-detail.html">Product Default</a></li>
                                        <li><a class="dropdown-item nav-link nav_item" href="product-detail-left-sidebar.html">Product Left Sidebar</a></li>
                                        <li><a class="dropdown-item nav-link nav_item" href="product-detail-right-sidebar.html">Product Right Sidebar</a></li> 
                                    </ul>
                                </li>
                                <li class="mega-menu-col col-lg-3">
                                    <ul> 
                                        <li class="dropdown-header">Extra</li> 
                                        <li><a class="dropdown-item nav-link nav_item" href="cart.html">Cart</a></li>
                                        <li><a class="dropdown-item nav-link nav_item" href="checkout.html">Checkout</a></li>
                                        <li><a class="dropdown-item nav-link nav_item" href="wishlist.html">Wishlist</a></li> 
                                        <li><a class="dropdown-item nav-link nav_item" href="my-account.html">My Account</a></li> 
                                    </ul>
                                </li>
                                <li class="mega-menu-col col-lg-3">
                                    <div class="ads_banner">
                                    	<a href="#"><img src="assets/images/mega_menu_ads.jpg" alt="mega_menu_ads"/></a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle nav-link" href="#" data-toggle="dropdown">كن شريكاً</a>
                        <div class="dropdown-menu">
                            <ul> 
                                <li><a class="dropdown-item nav-link nav_item" href="team.html">Our Team</a></li>
                                <li><a class="dropdown-item nav-link nav_item dropdown-toggler" href="#">Gallery</a>
                                	<div class="dropdown-menu">
                                        <ul> 
                                            <li><a class="dropdown-item nav-link nav_item" href="gallery-three-columns.html">Grid 3 Columns</a></li>
                                            <li><a class="dropdown-item nav-link nav_item" href="gallery-four-columns.html">Grid 4 Columns</a></li>
                                            <li><a class="dropdown-item nav-link nav_item" href="gallery-three-columns-wide.html">Grid 3 Columns Wide</a></li>
                                            <li><a class="dropdown-item nav-link nav_item" href="gallery-four-columns-wide.html">Grid 4 Columns Wide</a></li>
                                            <li><a class="dropdown-item nav-link nav_item" href="gallery-masonry-three-columns.html">Masonry 3 Columns</a></li>
                                            <li><a class="dropdown-item nav-link nav_item" href="gallery-masonry-four-columns.html">Masonry 4 Columns</a></li>
                                            <li><a class="dropdown-item nav-link nav_item" href="gallery-masonry-three-columns-wide.html">Masonry 3 Columns Wide</a></li>
                                            <li><a class="dropdown-item nav-link nav_item" href="gallery-masonry-four-columns-wide.html">Masonry 4 Columns Wide</a></li>
                                            <li><a class="dropdown-item nav-link nav_item" href="gallery-detail.html">Gallery Detail</a></li>
                                        </ul>
                                    </div>
                                </li>  
                                <li><a class="dropdown-item nav-link nav_item" href="faq.html">FAQ</a></li> 
                                <li><a class="dropdown-item nav-link nav_item" href="coming-soon.html">Coming Soon</a></li>
                                <li><a class="dropdown-item nav-link nav_item" href="404.html">404 Page</a></li>
                            </ul>
                        </div>
                    </li>
                    <li>
                        <a class="nav-link" href="/">إشترك اﻵن</a>
                    </li>
                </ul>
            </div>
            <ul class="navbar-nav attr-nav align-items-center">
                <li><a href="javascript:void(0);" class="nav-link search_trigger"><i class="ion-ios-search-strong"></i></a>
                    <div class="search-overlay">
                        <div class="search_wrap">
                            <form>
                                <div class="rounded_input">
                                	<input type="text" placeholder="Search" class="form-control" id="search_input">
                                </div>
                                <button type="submit" class="search_icon"><i class="fas fa-search"></i></button>
                            </form>
                        </div>
                    </div>
                </li>
                <li class="dropdown cart_wrap">
                	<a class="nav-link" href="#" data-toggle="dropdown"><i class="ion-bag"></i><span class="cart_count">2</span></a>
                        <div class="cart_box dropdown-menu dropdown-menu-right">
                            <ul class="cart_list">
                                <li>
                                    <a href="#" class="item_remove"><i class="ion-close"></i></a>
                                    <a href="#"><img src="assets/images/cart_thamb1.jpg" alt="cart_thumb1">Fresh Organic Strawberry</a>
                                    <span class="cart_quantity"> 1 x <span class="cart_amount"> <span class="price_symbole">$</span>78.00</span></span>
                                </li>
                                <li>
                                    <a href="#" class="item_remove"><i class="ion-close"></i></a>
                                    <a href="#"><img src="assets/images/cart_thamb2.jpg" alt="cart_thumb2">Fresh Organic Grapes</a>
                                    <span class="cart_quantity"> 1 x <span class="cart_amount"> <span class="price_symbole">$</span>81.00</span></span>
                                </li>
                            </ul>
                        <div class="cart_footer">
                            <p class="cart_total">Total: <span class="cart_amount"> <span class="price_symbole">$</span>159.00</span></p>
                            <p class="cart_buttons"><a href="cart.html" class="btn btn-default btn-radius view-cart">View Cart</a><a href="checkout.html" class="btn btn-dark btn-radius checkout">Checkout</a></p>
                        </div>
                    </div>
                </li>
            </ul>
        </nav>
    </div>
</header>
<!-- END HEADER --> 

resources/views/partials/sidebar.blade.php
<aside id="sidebar" class="col-lg-4 col-md-12">
    <div class="widget">
        <div class="widget-bg">
            <div class="team-holder">
                <div class="team-item flex-row justify-content-center">
                    <a href="#" class="member-photo">
                        <img src="http://brainwavescience.com/wp-content/uploads/2017/06/testi.png" alt="" width="104" height="104">
                    </a>
                    <div class="team-desc">
                        <div class="member-info align-center">
                            <h6 class="member-name">{{ $user->full_name }}</h6>
                            <h6 class="member-name">رقم العضوية: <b>#{{ $user->member_id }}</b></h6>
                            <h6 class="member-name">الرصيد: <b>{{ $user->balance }} ريال</b></h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="widget">
        <div class="widget-bg">
            <div class="pbar-holder">
                <div class="pbar-wrap">
                    <!-- من اصل جميع التمارين -->
                    <div class="pbar-title">التمارين المسجلة <span>{{ auth()->user()->getExercisePercentage() }}%</span></div>
                    <div class="pbar">
                        <div class="pbar-inner" style="width: {{ auth()->user()->getExercisePercentage() }}%"></div>
                    </div>
                </div>
                <div class="pbar-wrap">
                    <!-- من اصل جميع الحجوزات -->
                    <div class="pbar-title">الحصص المؤكدة <span>{{ auth()->user()->getConfimredBookingPercentage() }}%</span></div>
                    <div class="pbar">
                        <div class="pbar-inner" style="width: {{ auth()->user()->getConfimredBookingPercentage() }}%"></div>
                    </div>
                </div>
                <div class="pbar-wrap">
                    <!-- حساب نسبة اﻻلغاء قبل الوقت -->
                    <div class="pbar-title">اﻹلتزام بالحضور <span>{{ auth()->user()->getCancellationPercentage() }}%</span></div>
                    <div class="pbar">
                        <div class="pbar-inner" style="width: {{ auth()->user()->getCancellationPercentage() }}%"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</aside>